GET http://localhost:3001/api/notes/

###
GET http://localhost:3001/api/notes/62ceabd70507e06a6dcfcf74

###
GET http://localhost:3001/api/notes/62d7db27218d615f36757968

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "This is a new note",
  "important": false
}

###
DELETE http://localhost:3001/api/notes/62d7db27218d615f36757968